### ISSUE TITLE
Falling through block when getting up in certain situations

### ISSUE THREAD

**Issue by FC-Creations** [bl4ckscor3/Sit#28] opened 2023-02-11 18:27 UTC
If you initiate sitting from a slab or any block that is less than a full block (path blocks, trap doors, chests, etc) when you stand, it appears it teleports you inside the partial block, instead of on top of it. If there's no blocks under the partial block, you will fall through it.

**Comment by bl4ckscor3** [comment] 2023-02-11 20:03
Duplicate of #22, fixed as of v1.3.2.

**Closed as not planned by bl4ckscor3** 2023-02-11 20:03 UTC
Labels: bug, duplicate
